### ISSUE TITLE
Issues with the coming version of scales

### ISSUE THREAD

**Issue by thomasp85** [openanalytics/inTextSummaryTable#4]
Hi

I'm writing to let you know that we plan to release the next version of scales in 2 weeks and we have detected a small issue in the unit tests of your package. It is pretty benign and originates in a fix for range ordering when training factors and character vectors

```r
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(inTextSummaryTable)
  > 
  > test_check("inTextSummaryTable")
  [ FAIL 2 | WARN 3 | SKIP 0 | PASS 991 ]
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
...
  2/2 mismatches
  x[1]: "red"
  y[1]: "blue"
  
  x[2]: "blue"
  y[2]: "red"
  
  [ FAIL 2 | WARN 3 | SKIP 0 | PASS 991 ]
  Error: Test failures
  Execution halted
```

**Comment by lcougnaud** [comment]
Dear @thomasp85 ,
The latest version of the package (v3.3.2) has been tested with the latest scales version (v1.3.0) and all the tests pass with this version. So I will now close that issue.
But thanks for the notifications anyway!
