### ISSUE TITLE
Issues with the dev version of flextable

### ISSUE THREAD

**Issue by davidgohel** [openanalytics/inTextSummaryTable#5]
Hello,

We plan to release the next version of flextable in few weeks and there is an issue in one test of your package: https://github.com/openanalytics/inTextSummaryTable/blob/master/inTextSummaryTable/tests/testthat/test_exportSummaryStatisticsTable-flextable.R

A recent modification resulted in a change of some data structures. "test_exportSummaryStatisticsTable-flextable.R" uses the internal structures of flextable, for example: `x[[part]]$content$content` no longer exists. These structures are undocumented and non-exported and their usage in other packages are not recommended; only documented and exported functions should be used.

I would prefer if you could delete the test file. But if you don't want to, I've temporarily exported 3 functions to help you make the transition. These should let you replace your usage of flextable structure (even if I think that’s a bad idea because I want to be free to change internals of flextable) :
 
- `information_data_cell()`
- `information_data_chunk()`
- `information_data_paragraph()`

KR
David

**Comment by lcougnaud** [comment]
Dear @davidgohel ,

Thanks for the notification of the update of flextable.
The inTextSummaryTable version 3.3.2 (on its way to CRAN) includes some fixes of the tests (commit: 4d3d8cb96fe9455f2304c52d074b1090f3470681), using the new  `information_data_chunk` function.

As the package is used in a regulatory environment for the creation of in-text tables for clinical trials, I would like to keep the tests for (most of) the functionalities of the inTextSummaryTable package. The new `information_xxx` functions (i.e.`information_data_chunk`) makes it easier for me to test specific functionalities of my package (e.g. inclusion of superscript/subscript) directly from the flextable output object (via the new  functions) .
Would you have (by any chance) any idea of another way to test such functionalities?

Thanks again for the help and the great package!

**Comment by davidgohel** [comment]
Hello 

Thanks for the update

> Would you have (by any chance) any idea of another way to test such functionalities?

Yes, with visual testing. Since more than a year, it is possible to use `grid` output which make possible to "visual test"... I met an issue with one Linux platform, all other platforms give the same graphic. So that's the issue I need to solve. If I succeed in understanding what is needed to produce the same result on any platform (I suspect cairo or freetype to be the root of the problem), I'll let you know. I can also perform visual testing of Word document with `doconv::expect_snapshot_doc()` but it relies on the availability of Word on the machine which makes impossible to test on CI/CD...
